# Generated by Django 6.0.7 on 2026-07-30 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_historia_clinica', models.CharField(help_text='Número único de historia clínica', max_length=50, unique=True)),
                ('dni', models.CharField(blank=True, help_text='Documento de identidad del paciente', max_length=8, null=True)),
                ('nombre_completo', models.CharField(help_text='Nombre completo del paciente', max_length=255)),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento del paciente')),
                ('necesita_examen', models.BooleanField(default=False, help_text='El paciente necesita examen de laboratorio?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['numero_historia_clinica'], name='consultorio_numero__73caa3_idx'), models.Index(fields=['dni'], name='consultorio_dni_61ddde_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la historia clínica')),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico del paciente', null=True)),
                ('tratamiento', models.TextField(blank=True, help_text='Tratamiento recomendado', null=True)),
                ('receta_medica', models.TextField(blank=True, help_text='Receta médica prescrita', null=True)),
                ('paciente', models.OneToOneField(help_text='Referencia al paciente', on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='consultorio_externo.paciente')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de la cita')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_TRIAGE', 'En Triaje'), ('EN_CONSULTA', 'En Consulta'), ('FINALIZADA', 'Finalizada')], default='PROGRAMADA', help_text='Estado actual de la cita', max_length=20)),
                ('paciente', models.ForeignKey(help_text='Referencia al paciente', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='consultorio_externo.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['paciente', 'fecha_hora'], name='consultorio_pacient_711b36_idx'), models.Index(fields=['estado'], name='consultorio_estado_4d83e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeticionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(help_text='Tipo de examen solicitado', max_length=255)),
                ('tiene_sis', models.BooleanField(default=False, help_text='El examen está cubierto por el SIS?')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, help_text='Fecha de solicitud del examen')),
                ('paciente', models.ForeignKey(help_text='Referencia al paciente', on_delete=django.db.models.deletion.CASCADE, related_name='peticiones_prueba', to='consultorio_externo.paciente')),
            ],
            options={
                'verbose_name': 'Petición de Prueba',
                'verbose_name_plural': 'Peticiones de Prueba',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['paciente', 'fecha_solicitud'], name='consultorio_pacient_ebcd65_idx')],
            },
        ),
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del triaje')),
                ('presion_sistolica', models.IntegerField(help_text='Presión sistólica (mmHg)')),
                ('presion_diastolica', models.IntegerField(help_text='Presión diastólica (mmHg)')),
                ('temperatura', models.FloatField(help_text='Temperatura corporal (°C)')),
                ('paciente', models.ForeignKey(help_text='Referencia al paciente', on_delete=django.db.models.deletion.CASCADE, related_name='triajes', to='consultorio_externo.paciente')),
            ],
            options={
                'verbose_name': 'Triaje',
                'verbose_name_plural': 'Triajes',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['paciente', 'fecha_hora'], name='consultorio_pacient_60d3c3_idx')],
            },
        ),
    ]
