# Generated by Django 6.0.7 on 2026-07-21 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('especialidad', models.CharField(max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenInternamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad_solicitada', models.CharField(max_length=50)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('medico_solicitante', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADA', 'Validada'), ('RECHAZADA', 'Rechazada'), ('EN_ESPERA', 'En lista de espera'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('signos_vitales', models.JSONField(default=dict)),
                ('plan_medico', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ALTA', 'Alta'), ('TRANSFERIDA', 'Transferida')], default='ACTIVA', max_length=20)),
                ('cama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admision_hospitalizacion.cama')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admision_hospitalizacion.ordeninternamiento')),
            ],
        ),
        migrations.AddField(
            model_name='ordeninternamiento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision_hospitalizacion.paciente'),
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamientos', models.TextField(blank=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('hospitalizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admision_hospitalizacion.hospitalizacion')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admision_hospitalizacion.paciente')),
            ],
        ),
    ]
