# Generated by Django 6.0.7 on 2026-07-21 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100)),
                ('num_serie', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_adq', models.DateField(blank=True, db_column='fecha_adquisicion', null=True)),
                ('fecha_ult_calib', models.DateField(blank=True, db_column='fecha_ultima_calibracion', null=True)),
                ('estado', models.CharField(default='OPER', max_length=30)),
            ],
            options={
                'verbose_name': 'Equipo Biomedico',
                'verbose_name_plural': 'Equipos Biomedicos',
                'db_table': 'mb_equipo_biomedico',
            },
        ),
        migrations.CreateModel(
            name='Estimacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(db_column='precio_estimado', decimal_places=2, max_digits=12)),
                ('proveedor', models.CharField(max_length=200)),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha_estimacion')),
            ],
            options={
                'verbose_name': 'Estimacion de Precios',
                'verbose_name_plural': 'Estimaciones de Precios',
                'db_table': 'mb_estimacion_precios',
            },
        ),
        migrations.CreateModel(
            name='Presup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.CharField(db_column='numero_documento', max_length=100)),
                ('monto', models.DecimalField(db_column='monto_aprobado', decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(blank=True, db_column='fecha_aprobacion', null=True)),
                ('estado', models.CharField(default='PEND', max_length=30)),
                ('estimacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='mantenimiento_biomedico.estimacion')),
            ],
            options={
                'verbose_name': 'Disponibilidad Presupuestaria',
                'verbose_name_plural': 'Disponibilidades Presupuestarias',
                'db_table': 'mb_disp_presupuestaria',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('reportado_por', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha_reporte')),
                ('estado', models.CharField(default='PEND', max_length=30)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='mantenimiento_biomedico.equipobio')),
            ],
            options={
                'verbose_name': 'Reporte de Equipo',
                'verbose_name_plural': 'Reportes de Equipos',
                'db_table': 'mb_reporte_equipo',
            },
        ),
        migrations.CreateModel(
            name='Interv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('tecnico', models.CharField(db_column='tecnico_responsable', max_length=200)),
                ('fecha_ini', models.DateTimeField(auto_now_add=True, db_column='fecha_inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='mantenimiento_biomedico.equipobio')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones', to='mantenimiento_biomedico.reporte')),
            ],
            options={
                'verbose_name': 'Intervencion',
                'verbose_name_plural': 'Intervenciones',
                'db_table': 'mb_intervencion',
            },
        ),
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=200)),
                ('diagnostico', models.TextField()),
                ('reemplazo', models.BooleanField(db_column='requiere_reemplazo', default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha_evaluacion')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='mantenimiento_biomedico.reporte')),
            ],
            options={
                'verbose_name': 'Evaluacion Tecnica',
                'verbose_name_plural': 'Evaluaciones Tecnicas',
                'db_table': 'mb_evaluacion_tecnica',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='fecha_solicitud')),
                ('estado', models.CharField(default='PEND', max_length=30)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reemplazo', to='mantenimiento_biomedico.equipobio')),
                ('eval', models.ForeignKey(db_column='evaluacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='mantenimiento_biomedico.eval')),
            ],
            options={
                'verbose_name': 'Solicitud de Reemplazo',
                'verbose_name_plural': 'Solicitudes de Reemplazo',
                'db_table': 'mb_solicitud_reemplazo',
            },
        ),
        migrations.AddField(
            model_name='estimacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimaciones', to='mantenimiento_biomedico.solicitud'),
        ),
    ]
