# Generated by Django 6.0.7 on 2026-07-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento_biomedico', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presup',
        ),
    ]
